---
port: 3001
baseURL: "https://audio.ury.org.uk"
streams:
    - name: "Broadcast"
      endpoint: "live-high"
    - name: "OB Line"
      endpoint: "OB-Line"
    - name: "OB Line 2"
      endpoint: "OB-Line2"
    - name: "Roses Internal 1"
      endpoint: "roses-internal-1"
    - name: "Roses Internal 2"
      endpoint: "roses-internal-2"
    - name: "Roses Internal 3"
      endpoint: "roses-internal-3"      
    - name: "Roses Internal 4"
      endpoint: "roses-internal-4"      
    - name: "Roses Internal 5"
      endpoint: "roses-internal-5"
    - name: "Roses Internal 6"
      endpoint: "roses-internal-6"            
    - name: "Roses Internal 7"
      endpoint: "roses-internal-8"
    - name: "Roses External 1"
      endpoint: "roses-out-1"
    - name: "Roses External 2"
      endpoint: "roses-out-2"
    - name: "Roses External 3"
      endpoint: "roses-out-3"
    - name: "Roses External 4"
      endpoint: "roses-out-4"
    - name: "Roses External 5"
      endpoint: "roses-out-5"
    - name: "Roses External 6"
      endpoint: "roses-out-6"
    - name: "Roses External 7"
      endpoint: "roses-out-7"
    - name: "Roses External 8"
      endpoint: "roses-out-8"                                          
