---
port: 3000
baseURL: "https://audio.ury.org.uk"
streams:
    - name: "OB Line"
      endpoint: "OB-Line"
    - name: "OB Line 2"
      endpoint: "OB-Line2"
    - name: "Roses Stream 1"
      endpoint: "Roses1"
    - name: "Roses Stream 2"
      endpoint: "Roses2"
    - name: "Roses Stream 3"
      endpoint: "Roses3"
    - name: "Roses Stream 4"
      endpoint: "Roses4"
